# Import the required modules and libraries
from django.urls import path, include  # Importing Django's path and include function
from rest_framework.routers import DefaultRouter  # Importing DefaultRouter from Django REST Framework
from myapp import views  # Importing your custom views
from myapp.views import Authenticate, Signup, CustomUserViewSet  # Importing specific view classes

# Create a Default Router object
router = DefaultRouter()

# Register the CustomUserViewSet with the router
# This will automatically create CRUD routes for the CustomUser model
router.register(r"users", views.CustomUserViewSet)

# urlpatterns holds the URL patterns for this Django app
urlpatterns = [
    path("", include(router.urls)),  # Include all routes generated by the router
    path("authenticate/", Authenticate.as_view(), name="authenticate"),  # URL for the authentication view
    path("signup/", Signup.as_view(), name="signup"),  # URL for the signup view
]
